sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION != "5.6" ]]; then composer install; fi
  - if [[ $TRAVIS_PHP_VERSION = "5.6" ]]; then composer require satooshi/php-coveralls; fi

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then php vendor/bin/coveralls -v; fi
